sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  # --ignore-platform-reqs, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2722
  - composer update -n --prefer-dist --ignore-platform-reqs
  - composer require --dev php-coveralls/php-coveralls --ignore-platform-reqs

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

  - composer show

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose --coverage-php coverage/cov/main.cov
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache/files
